use utoipa::{
    Modify, OpenApi,
    openapi::security::{Http, HttpAuthScheme, SecurityScheme},
};
use utoipa_swagger_ui::SwaggerUi;

use crate::{
    analytics::dto::{
        AnalyticsCounts, AnalyticsOverviewResponse, DailyActivity, PerformanceAvailability,
        PnlAvailability, StatusCount, WorkflowActivity,
    },
    auth::dto::{
        AuthSessionResponse, AuthUserResponse, ConnectPolymarketRequest, CreateChallengeRequest,
        CreateChallengeResponse, ForgotPasswordRequest, LoginRequest, ResetPasswordRequest,
        SettingsUpdateResponse, SignupRequest, UpdateEmailRequest, UpdatePasswordRequest,
        VenueConnectionResponse, VerifyChallengeRequest, VerifyChallengeResponse,
        VerifyEmailRequest,
    },
    automations::dto::{
        AutomationAlertResponse, AutomationMarketPayload, AutomationProvider, AutomationResponse,
        AutomationStatus, AutomationStepKind, ClearAlertsResponse, MarkAlertsReadResponse,
        PublishAutomationRequest, TestRunAutomationRequest, TestRunAutomationResponse,
        UpdateAutomationStatusRequest, WorkflowActionType, WorkflowConnectionPayload,
        WorkflowPayload, WorkflowStepPayload,
    },
    error::ErrorResponse,
    mcp::dto::{
        McpApprovalDecisionResponse, McpApprovalResponse, McpJsonRpcRequest, McpJsonRpcResponse,
    },
    notifications::dto::AutomationAlertStreamEvent,
    polymarket::dto::{
        MarketsQuery, OrderBookLevelResponse, OrderBookResponse, PolymarketTokenMetadataResponse,
        VenueChainResponse,
    },
    response::ApiResponse,
    trades::dto::{
        CreateTradeIntentRequest, CreateTradeIntentResponse, PolymarketExecutionType,
        SubmitSignedTradeRequest, SubmitSignedTradeResponse, TradeIntentResponse, TradeOrderType,
        TradeSide,
    },
    users::handler::{
        TradingProviderResponse, UpdateTradingProviderRequest, UpdateWalletRequest,
        UserTradingProviderResponse, UserWalletResponse, WaitlistResponse, WaitlistUser,
    },
    venue::{SupportedChain, SupportedVenue},
};

#[derive(OpenApi)]
#[openapi(
    paths(
        super::health_check,
        crate::analytics::handlers::analytics_overview,
        crate::auth::handlers::signup,
        crate::auth::handlers::login,
        crate::auth::handlers::verify_email,
        crate::auth::handlers::forgot_password,
        crate::auth::handlers::reset_password,
        crate::auth::handlers::create_challenge,
        crate::auth::handlers::verify_challenge,
        crate::auth::handlers::current_user,
        crate::auth::handlers::update_email,
        crate::auth::handlers::update_password,
        crate::auth::handlers::connect_polymarket,
        crate::automations::handlers::list_automations,
        crate::automations::handlers::publish_automation,
        crate::automations::handlers::update_automation,
        crate::automations::handlers::update_automation_status,
        crate::automations::handlers::delete_automation,
        crate::automations::handlers::test_run_automation,
        crate::automations::handlers::list_alerts,
        crate::automations::handlers::clear_alerts,
        crate::automations::handlers::mark_alerts_read,
        crate::automations::handlers::mark_alert_read,
        crate::mcp::handlers::handle_mcp,
        crate::mcp::handlers::list_mcp_approvals,
        crate::mcp::handlers::get_mcp_approval,
        crate::mcp::handlers::approve_mcp_approval,
        crate::mcp::handlers::reject_mcp_approval,
        crate::notifications::handlers::stream_alerts,
        crate::polymarket::handlers::fetch_markets,
        crate::polymarket::handlers::fetch_market,
        crate::polymarket::handlers::fetch_order_book,
        crate::polymarket::handlers::fetch_venue_chain,
        crate::trades::handlers::list_trades,
        crate::trades::handlers::get_trade,
        crate::trades::handlers::create_trade_intent,
        crate::trades::handlers::submit_signed_trade,
        crate::users::handler::list_trading_providers,
        crate::users::handler::update_trading_provider,
        crate::users::handler::update_wallet,
        crate::users::handler::join_waitlist
    ),
    components(
        schemas(
            AnalyticsCounts,
            AnalyticsOverviewResponse,
            DailyActivity,
            PerformanceAvailability,
            PnlAvailability,
            StatusCount,
            WorkflowActivity,
            ApiResponse<AnalyticsOverviewResponse>,
            AuthUserResponse,
            AuthSessionResponse,
            AutomationAlertResponse,
            AutomationResponse,
            AutomationMarketPayload,
            AutomationProvider,
            AutomationAlertStreamEvent,
            AutomationStatus,
            AutomationStepKind,
            ApiResponse<AuthUserResponse>,
            ApiResponse<AuthSessionResponse>,
            ApiResponse<AutomationResponse>,
            ApiResponse<TestRunAutomationResponse>,
            ApiResponse<Vec<AutomationAlertResponse>>,
            ApiResponse<Vec<AutomationResponse>>,
            ApiResponse<MarkAlertsReadResponse>,
            ApiResponse<ClearAlertsResponse>,
            ApiResponse<McpApprovalResponse>,
            ApiResponse<McpApprovalDecisionResponse>,
            ApiResponse<Vec<McpApprovalResponse>>,
            ApiResponse<CreateChallengeResponse>,
            ApiResponse<String>,
            ApiResponse<VenueConnectionResponse>,
            ApiResponse<VerifyChallengeResponse>,
            ApiResponse<WaitlistResponse>,
            ApiResponse<OrderBookResponse>,
            ApiResponse<VenueChainResponse>,
            ApiResponse<Vec<TradingProviderResponse>>,
            ApiResponse<UserTradingProviderResponse>,
            ApiResponse<UserWalletResponse>,
            ApiResponse<SettingsUpdateResponse>,
            ApiResponse<Vec<TradeIntentResponse>>,
            ApiResponse<TradeIntentResponse>,
            ApiResponse<CreateTradeIntentResponse>,
            ApiResponse<SubmitSignedTradeResponse>,
            ConnectPolymarketRequest,
            CreateChallengeRequest,
            CreateChallengeResponse,
            ErrorResponse,
            ForgotPasswordRequest,
            LoginRequest,
            MarketsQuery,
            MarkAlertsReadResponse,
            ClearAlertsResponse,
            McpApprovalResponse,
            McpApprovalDecisionResponse,
            McpJsonRpcRequest,
            McpJsonRpcResponse,
            OrderBookLevelResponse,
            OrderBookResponse,
            PolymarketTokenMetadataResponse,
            VenueChainResponse,
            CreateTradeIntentRequest,
            CreateTradeIntentResponse,
            PolymarketExecutionType,
            SubmitSignedTradeRequest,
            SubmitSignedTradeResponse,
            TradeIntentResponse,
            TradeOrderType,
            TradeSide,
            PublishAutomationRequest,
            ResetPasswordRequest,
            SettingsUpdateResponse,
            SignupRequest,
            UpdateEmailRequest,
            UpdatePasswordRequest,
            TestRunAutomationRequest,
            TestRunAutomationResponse,
            TradingProviderResponse,
            UpdateAutomationStatusRequest,
            UpdateTradingProviderRequest,
            UpdateWalletRequest,
            WorkflowActionType,
            WorkflowConnectionPayload,
            WorkflowPayload,
            WorkflowStepPayload,
            UserTradingProviderResponse,
            UserWalletResponse,
            SupportedChain,
            SupportedVenue,
            VenueConnectionResponse,
            VerifyChallengeRequest,
            VerifyChallengeResponse,
            VerifyEmailRequest,
            WaitlistResponse,
            WaitlistUser
        )
    ),
    modifiers(&SecurityAddon),
    info(
        title = "Uptions Backend API",
        version = "1.0.0",
        description = "Versioned V1 backend endpoints for Uptions identity, venue connections, market discovery, and automation workflows."
    )
)]
struct ApiDoc;

pub fn swagger_ui() -> SwaggerUi {
    SwaggerUi::new("/docs").url("/docs/openapi.json", ApiDoc::openapi())
}

struct SecurityAddon;

impl Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        if let Some(components) = openapi.components.as_mut() {
            components.add_security_scheme(
                "bearer_auth",
                SecurityScheme::Http(Http::new(HttpAuthScheme::Bearer)),
            );
        }
    }
}
